# Continuous Integration (CI) pipeline that orchestrates the deployment of the mnist model to aks.
resources:
  containers:
  - container: mlops
    image: mcr.microsoft.com/mlops/python:latest
    
trigger:
  branches:
    include:
    - aks-deployment
  paths:
    include:
    - ml_service/endpoints

variables:
- group: devopsforai-aml-vg

stages:
- stage: 'Deploy_AKS'
  displayName: 'Deploy to AKS'
  jobs:
  - job: "Deploy_AKS"
    displayName: "Deploy to AKS"
    container: mlops
    timeoutInMinutes: 0
    steps:
    - task: AzureCLI@1
      displayName: 'Install AzureML CLI'
      inputs:
        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
        scriptLocation: inlineScript
        workingDirectory: $(Build.SourcesDirectory)
        inlineScript: 'az extension add -n azure-cli-ml'
    - task: AzureCLI@1
      displayName: 'Create Compute Target'
      inputs:
        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
        scriptLocation: inlineScript
        workingDirectory: $(Build.SourcesDirectory)
        inlineScript: 'az ml computetarget create aks --name mnist-cluster'
    - task: AzureCLI@1
      displayName: "Deploy to AKS (CLI)"
      inputs:
        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
        scriptLocation: inlineScript
        workingDirectory: $(Build.SourcesDirectory)/ml_service/endpoints
        inlineScript: |
          set -e # fail on error
          
          az ml model deploy --name mnist-aks --model sklearn_mnist:1 \
          --compute-target mnist-cluster \
          --ic inference_config.yml \
          --dc deployment_config_aks.yml \
          -g $(RESOURCE_GROUP) --workspace-name $(WORKSPACE_NAME) \
          --overwrite -v