# Continuous Integration (CI) pipeline that orchestrates the training of the mnist model.

# Trigger this pipeline on model-train pipeline completion
resources:
  containers:
  - container: mlops
    image: mcr.microsoft.com/mlops/python:latest
    
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - mnist/training/train.py
    - ml_service/pipelines/mnist_build_training_pipeline.py

variables:
- group: devopsforai-aml-vg

pool:
  vmImage: ubuntu-latest

stages:
- stage: 'Training_Pipeline_CI'
  displayName: 'Training Pipeline CI'
  jobs:
  - job: "Build_Training_Pipeline"
    displayName: "Build Training Pipeline"
    container: mlops
    timeoutInMinutes: 0
    steps:
    - task: AzureCLI@1
      displayName: "Publish Training Pipeline"
      name: publish_batchscore
      inputs:
        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'        
        scriptLocation: inlineScript
        workingDirectory: $(Build.SourcesDirectory)
        inlineScript: |
          set -e # fail on error
          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
          # Invoke the Python building and publishing a training pipeline
          pip install azureml.opendatasets --user
          python -m ml_service.pipelines.mnist_build_training_pipeline
      